name: housing-analysis
namespace: dev
role: housing-analysis
replicaCount: 1

docker:
  img: alirom93/projects:housing-analysis-0.1.3
  secret: myregistrykey
  pullPolicy: Always

consulAgent:
  consulServer: consul-consul-server
  configMap:
    name: consul-agent-config-map
    key: consulagent.conf
  gossipSecret:
    name: consul-join-key
    key: consul_key
