# Generated by Django 3.0.7 on 2020-07-02 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='indexTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regionID', models.IntegerField(default=0)),
                ('regionName', models.CharField(max_length=200)),
                ('regionState', models.CharField(max_length=200)),
            ],
        ),
    ]
