# Generated by Django 3.0.8 on 2020-07-08 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indextable',
            name='id',
        ),
        migrations.AlterField(
            model_name='indextable',
            name='regionID',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
