# Generated by Django 3.0.8 on 2020-07-13 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20200708_0519'),
    ]

    operations = [
        migrations.CreateModel(
            name='testState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testlist', models.IntegerField(default=0)),
            ],
        ),
    ]
