# Generated by Django 3.0.7 on 2020-06-14 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20200613_2220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price',
            name='price',
        ),
        migrations.AddField(
            model_name='price',
            name='home_value',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='price',
            name='rental_value',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='price',
            name='latest_date',
            field=models.DateTimeField(verbose_name='when data was collected'),
        ),
    ]
