# Generated by Django 3.0.8 on 2020-07-17 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_teststate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indextable',
            name='regionState',
            field=models.CharField(max_length=100),
        ),
    ]
