apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.consulAgent.configMap.name }}
  namespace: {{ .Values.namespace }}
  labels:
    role: {{ .Values.name }}-cluster
data:
  {{ .Values.consulAgent.configMap.key }}: |
    {
        "service": {
            "name": "housing-analysis",
            "tags": [
                "config-cluster"
            ],
            "port": 8000
        },
        "checks": [
            {
                "id": "endpoint",
                "name": "/myapp",
                "http": "http://localhost:8000",
                "interval": "15s"
            }
        ]
    }
