---
apiVersion: v1
kind: Service

metadata:
  name: {{ .Values.name }}-service
  namespace: {{ .Values.namespace }}
  labels:
    role: {{ .Values.role }}-service

spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP

  selector:
    pod: {{ .Values.role }}
