name: Build new Docker img
# This workflow is triggered on pushes to the repository.
#on: [push]
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Person to greet'
        required: true
        default: 'Mona the Octocat'

jobs:
  build:
    # Job name is Greeting
    name: Build Release Housing Analysis
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build Img
      run: |
        echo "Building release version: ${{ github.event.inputs.version }}"
        export VERSION=${{ github.event.inputs.version }}
        cd release
        echo "${{ secrets.DOCKER_SECRET }}" | docker login -u "alirom93" --password-stdin
        docker-compose build
        docker-compose push
